//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC_mvc.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorldCupDbEntities : DbContext
    {
        public WorldCupDbEntities()
            : base("name=WorldCupDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<Phase> Phases { get; set; }
        public virtual DbSet<Scorer> Scorers { get; set; }
        public virtual DbSet<WorldCup> WorldCups { get; set; }
        public virtual DbSet<CountryInGroup> CountryInGroups { get; set; }
        public virtual DbSet<ScorerInGame> ScorerInGames { get; set; }
    }
}
