//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Game()
        {
            this.ScorerInGames = new HashSet<ScorerInGame>();
        }
    
        public int Game_Id { get; set; }
        public int Score1_90 { get; set; }
        public int Score2_90 { get; set; }
        public Nullable<int> Score1_120 { get; set; }
        public Nullable<int> Score2_120 { get; set; }
        public Nullable<int> PK1 { get; set; }
        public Nullable<int> PK2 { get; set; }
        public int Group_Id { get; set; }
        public int WC_Id { get; set; }
        public int Country_Id1 { get; set; }
        public int Country_Id2 { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual Group Group { get; set; }
        public virtual WorldCup WorldCup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScorerInGame> ScorerInGames { get; set; }
    }
}
