//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phase
    {
        public int Phase_Id { get; set; }
        public string PhaseName { get; set; }
        public int WC_Id { get; set; }
    
        public virtual WorldCup WorldCup { get; set; }
    }
}
