//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScorerInGame
    {
        public int Amount { get; set; }
        public int Scorer_Id { get; set; }
        public int Game_Id { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual Scorer Scorer { get; set; }
    }
}
