//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WC_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scorer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Scorer()
        {
            this.ScorerInGames = new HashSet<ScorerInGame>();
        }
    
        public int Scorer_Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public int Country_Id { get; set; }
    
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScorerInGame> ScorerInGames { get; set; }
    }
}
